##################################################
# Generated by phansible.com
##################################################

Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.name = "slim-auth.dev"
        v.customize ["modifyvm", :id, "--memory", 512]
    end

    config.vm.box = "trusty64"
    config.vm.box_url = "https://vagrantcloud.com/ubuntu/trusty64/version/1/provider/virtualbox.box"

    config.vm.network :private_network, ip: "192.168.56.102"
    config.ssh.forward_agent = true

    #############################################################
    # Ansible provisioning (you need to have ansible installed)
    #############################################################

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
    end

    config.vm.synced_folder "./", "/vagrant", id: "vagrant-root", 
        :nfs => false,
        owner: "vagrant",
        group: "www-data",
        mount_options: ["dmode=775,fmode=664"]

    # config.vm.synced_folder "./templates/cache", "/vagrant/templates/cache", id: "twig-template-cache",
    #     owner: "vagrant",
    #     group: "www-data",
    #     mount_options: ["dmode=775,fmode=664"]
end
