- name: Install php5-fpm and php5-cli
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-fpm
    - php5-cli

- name: Set error reporting
  sudo: yes
  lineinfile: dest={{ php_fpm_ini }}
              regexp='^error_reporting ='
              line='error_reporting = {{ php_error_reporting }}'
  notify: restart php5-fpm

- name: Set display_errors
  sudo: yes
  lineinfile: dest={{ php_fpm_ini }}
              regexp='^display_errors ='
              line='display_errors = {{ php_display_errors }}'
  notify: restart php5-fpm

- name: Set display_startup_errors
  sudo: yes
  lineinfile: dest={{ php_fpm_ini }}
              regexp='^display_startup_errors ='
              line='display_startup_errors = {{ php_display_startup_errors }}'
  notify: restart php5-fpm

- name: Set html_errors
  sudo: yes
  lineinfile: dest={{ php_fpm_ini }}
              regexp='^html_errors ='
              line='html_errors = {{ php_html_errors }}'
  notify: restart php5-fpm
